DjangoBookingSite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/deleteComfirmed', views.deleteComfirmed, name='deleteComfirmed'),
    path('<int:pk>/edit', views.edit, name='edit'),
]

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'Kajetan.Mieloch2002',
        }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'Password123.',
        }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'Kajetan.Mieloch2002',
        }))
    
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'example@example.com',
        }))
    
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'Password123.',
        }))
    
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'w-full px-3 py-4 mb-3 text-sm leading-tight text-gray-700 border rounded shadow appearance-none focus:outline-none focus:shadow-outline',
        'placeholder': 'Password123.',
        }))

core/views.py
from django.shortcuts import render, redirect

from item.models import Category, Item

from .forms import SignupForm

def index(request):
    items = Item.objects.filter(is_reserved=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'core/index.html', {
        'categories': categories,
        'items': items,
    })

def contact(request):
    return render(request, 'core/contact.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            
            return redirect('/login')
    else:
        form = SignupForm()
    
    return render(request, 'core/signup.html', {
        'form': form,
    })

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <script src="https://cdn.tailwindcss.com"></script>

    <title>{% block title %}{% endblock %}</title>
</head>
<body class="bg-indigo-300">
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200"
        style="background-color: #f5f5f5;">
        <div>
            <a href="/" class="text-2xl font-bold text-indigo-950">Kajetan Mieloch Hotel Site</a>
        </div>
        <div class="space-x-6">
            <a href="{% url 'item:new' %}" class="text-gray-600 hover:text-gray-800">New hotel</a>
            <a href="/#" class="text-gray-600 hover:text-gray-800">Browse</a>

            {% if request.user.is_authenticated %}
            <a href="{% url 'dashboard:index' %}" class="px-6 py-2 bg-indigo-950 text-white rounded hover:bg-indigo-900">Dashboard</a>
            <a href="{% url 'core:logout' %}" class="px-6 py-2 bg-indigo-950 text-white rounded hover:bg-indigo-900">Log out</a>
            {% else %}
            <a href="{% url 'core:signup' %}" class="px-6 py-2 bg-indigo-950 text-white rounded hover:bg-indigo-900">Sing up</a>
            <a href="{% url 'core:login' %}" class="px-6 py-2 bg-indigo-950 text-white rounded hover:bg-indigo-900">Sing in</a>
            {% endif %}
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-indigo-950">
        <div class="w-2/3 pr-10">
            <h3 class="text-gray-200 text-2xl font-bold">Kajetan Mieloch Hotel Site</h3>
            <p class="text-gray-400">Never say i had never done django app</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-bold text-gray-300">Menu</h3>
            <ul class="text-gray-400">
                <li class="mb-2"><a href="/#" class="hover:text-gray-200">Home Page</a></li>
                <li class="mb-2"><a href="{% url 'core:contact' %}" class="hover:text-gray-200">Contact</a></li>
                <li class="mb-2"><a href="/#" class="hover:text-gray-200">About</a></li>
                <li class="mb-2"><a href="/#" class="hover:text-gray-200">Privacy policy</a></li>
                <li class="mb-2"><a href="/#" class="hover:text-gray-200">TOS</a></li>

</body>
</html>

core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>Send any questions</h1>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl font-bold text-center">Newest hotels</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:detail' item.id %}">
                        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="w-full rounded-xl">
                    </a>


                <div class="p-6 bg-white rounded-b-xl">
                    <h3 class="mb-2 text-xl font-bold">{{ item.name }}</h3>
                    <p class="mb-4 text-gray-500">{{ item.description }}</p>
                    <p class="text-2xl font-bold">{{ item.price }} PLN</p>
                </div>
            </div>
            {% endfor %}
        </div>

    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl font-bold text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl ">
                        <h2 class="mb-2 text-xl font-bold">{{ category.name }}</h2>
                        <p class="mb-4 text-gray-500">{{ category.description }}</p>
                        <img src="{{ category.image.url }}" alt="{{ category.name }}" class="object-cover h-48 w-96 rounded-2xl">
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>

{% endblock %}

core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="text-2xl text-center font-bold py-4">Log in</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Username</label><br>
                {{ form.username }}<br>
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Password</label><br>
                {{ form.password }}<br>
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl"
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                </div>

                {{ form.non_field_errors }}

            {% endif %}

            <br><button class="py-4 px-8 bg-indigo-900 hover:bg-indigo-800 text-white font-bold py-2 px-4 rounded" type="submit">Sign up</button>

        </form>
    </div>

{% endblock %}

core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
    <div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
        <h1 class="text-2xl text-center font-bold py-4">Sign up</h1>

        <form method="post" action=".">
            {% csrf_token %}

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Username</label><br>
                {{ form.username }}<br>
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Email</label><br>
                {{ form.email }}<br>
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Password</label><br>
                {{ form.password1 }}<br>
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2" for="username">Repeat password</label><br>
                {{ form.password2 }}<br>
            </div>

            {% if form.errors or form.non_field_errors %}
                <div class="mb-3 p-6 bg-red-100 rounded-xl"
                    {% for field in form %}
                        {{ field.errors }}
                    {% endfor %}
                </div>

                {{ form.non_field_errors }}

            {% endif %}

            <br><button class="py-4 px-8 bg-indigo-900 hover:bg-indigo-800 text-white font-bold py-2 px-4 rounded" type="submit">Sign up</button>

        </form>
    </div>

{% endblock %}