DjangoBookingSite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/deleteComfirmed', views.deleteComfirmed, name='deleteComfirmed'),
    path('<int:pk>/edit', views.edit, name='edit'),
]

item/models.py
from django.contrib.auth.models import User
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    image = models.ImageField(upload_to='categories')
    
    class Meta:
        verbose_name = 'Category'

    def __str__(self):
        return self.name

class Item(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    is_reserved = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='item_images')

    class Meta:
        verbose_name = 'Item'

    def __str__(self):
        return self.name

item/forms.py
from django import forms

from .models import Category, Item

INPUT_CLASSES = 'w-full px-3 py-2 border rounded shadow-inner'


class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'category', 'image')
        
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
                }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
                }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
                }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
                }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
                }),
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('name', 'description', 'price', 'category', 'image', 'is_reserved')
        
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
                }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
                }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
                }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
                }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
                }),
            'is_reserved': forms.CheckboxInput(attrs={
                'class': INPUT_CLASSES
                }),
        }

item/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import NewItemForm, EditItemForm
from .models import Category, Item

def detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    related_items = Item.objects.filter(category=item.category, is_reserved=False).exclude(pk=item.pk)[0:3]

    return render(request, 'item/detail.html', {
        'item': item,
        'related_items': related_items,
    })

@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            
            return redirect('item:detail', pk=item.pk)
    else:
        form = NewItemForm()
    
    return render(request, 'item/new.html', {
        'form': form,
        'title': 'New Item',
    })

@login_required
def edit(request, pk):
        
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    
    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)
        print("post")
        if form.is_valid():
            print('valid')
            item.save()
            
            return redirect('item:detail', pk=item.pk)
    else:
        form = EditItemForm(instance=item)
    
    return render(request, 'item/new.html', {
        'form': form,
        'title': 'Edit Item',
    })


@login_required
def delete(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
  
    return render(request, 'item/deleteConfirmation.html',{
        'item': item
        })

@login_required
def deleteComfirmed(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)
    item.delete()
    
    return redirect('dashboard:index')

item/templates/item/deleteConfirmation.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
    <div class="mt-6 p-6 bg-white rounded-xl">
        <p class="text-xl font-semibold text-gray-600">Are you sure you want to delete "{{ item.name }}"? This action is not reversible.</p>
        <div class="flex justify-center items-center">
            <a href="{% url 'item:deleteComfirmed' item.id %}" class="inline-block px-6 py-2 mt-6 mr-4 text-lg font-semibold text-white uppercase transition duration-800 bg-red-700 rounded-xl hover:bg-red-600">Delete</a>
            <a href="{% url 'dashboard:index' %}" class="inline-block px-6 py-2 mt-6 text-lg font-semibold text-white uppercase transition duration-800 bg-gray-700 rounded-xl hover:bg-gray-600">Take me home</a>
        </div>
    </div>

{% endblock %}

item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{ item.image.url }}" alt="{{ item.name }}" class="rounded-xl">
    </div>

    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="text-3xl font-bold">{{ item.name }}</h1>
        <p class="text-xl font-semibold text-gray-600">Category: {{ item.category }}</p>
        <p class="text-xl font-semibold text-gray-600">Price: {{ item.price }}$</p>
        <p class="text-xl font-semibold text-gray-600">Description: {{ item.description }}</p>
        {% if request.user == item.created_by %}
            <div class="mt-6 p-6 bg-white rounded-xl">
                <p>This is your listing!</p>
                <a href="{% url 'item:edit' item.id %}" class="inline-block px-6 py-2 mt-6 text-lg font-semibold text-white uppercase transition duration-800 bg-green-700 rounded-xl hover:bg-green-600">Edit</a>
                <a href="{% url 'item:delete' item.id %}" class="inline-block px-6 py-2 mt-6 text-lg font-semibold text-white uppercase transition duration-800 bg-red-700 rounded-xl hover:bg-red-600">Delete</a>
            </div>
        {% endif %}
        <a href="#" class="inline-block px-6 py-2 mt-6 text-lg font-semibold text-white uppercase transition duration-800 bg-indigo-800 rounded-xl hover:bg-indigo-600">Book now!</a>
    </div>

</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl font-bold text-center">Related items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
            <div>
                <a href="{% url 'item:detail' item.id %}">
                    <img src="{{ item.image.url }}" alt="{{ item.name }}" class="w-full rounded-xl">
                </a>


            <div class="p-6 bg-white rounded-b-xl">
                <h3 class="mb-2 text-xl font-bold">{{ item.name }}</h3>
                <p class="mb-4 text-gray-500">{{ item.description }}</p>
                <p class="text-2xl font-bold">{{ item.price }} PLN</p>
            </div>
        </div>
        {% endfor %}
    </div>

</div>

{% endblock %}

item/templates/item/new.html
{% extends "core/base.html" %}

{% block title %}{{title}}{% endblock%}

{% block content %}
<h1 class="text-center text-4xl font-bold">{{title}}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <div class="space-2">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl"
        {% for field in form %}
            {{ field.errors }}
        {% endfor %}
    </div>

    {{ form.non_field_errors }}

    {% endif %}

    <br><button class="py-4 px-8 bg-indigo-900 hover:bg-indigo-800 text-white font-bold py-2 px-4 rounded" type="submit">Submit</button>
</form>
{% endblock  %}